Revert "Rename to filepath"

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -5,9 +5,9 @@ inputs:
   parser:
     required: true
     description: "Which parser to use."
-  filepath:
+  paths:
     required: false
-    description: "Filepath to check target: [file|dir|glob]"
+    description: "Paths to format target: [file/dir/glob ...]"
   prettier-version:
     default: "2.5.1"
     required: false
@@ -47,30 +47,30 @@ runs:
       run: |
         node_modules/.bin/prettier --version
 
-    - name: Create default filepath from parser
+    - name: Create default paths from parser
       shell: bash
-      id: default-filepath
+      id: default-paths
       env:
         PARSER: ${{ inputs.parser }}
-        FILEPATH: ${{ inputs.filepath }}
+        PATHS: ${{ inputs.paths }}
       run: |
-        if [[ "${FILEPATH}" != "" ]]; then
-          echo "::set-output name=filepath::${FILEPATH}"
+        if [[ "${PATHS}" != "" ]]; then
+          echo "::set-output name=paths::${PATHS}"
           exit 0
         fi
         case "${PARSER}" in
-          "yaml" ) echo '::set-output name=filepath::**/*.y*ml' ;;
-          "markdown" ) echo '::set-output name=filepath::**/*.md' ;;
-          * ) echo 'error: undefined filepath'; exit 1 ;;
+          "yaml" ) echo '::set-output name=paths::**/*.y*ml' ;;
+          "markdown" ) echo '::set-output name=paths::**/*.md' ;;
+          * ) echo 'error: undefined paths'; exit 1 ;;
         esac
 
     - name: Run prettier
       shell: bash
       env:
         PARSER: ${{ inputs.parser }}
-        FILEPATH: ${{ steps.default-filepath.outputs.filepath }}
+        PATHS: ${{ steps.default-paths.outputs.paths }}
       run: |
-        node_modules/.bin/prettier --parser="${PARSER}" --check "${FILEPATH}"
+        node_modules/.bin/prettier --parser="${PARSER}" --check "${PATHS}"
 
 # https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#branding
 branding:
